### PR TITLE
Fix: Re-added swap_columns_and_rows closes #264

### LINKED ISSUE #264: Changing split mode of existing tiles?
IIRC, i3 let me change the split mode of existing tiles / windows.

E.g.
go from

```
A
B
```
to
```
AB
```

It's been a while since I used i3. Most recently I used chunkwm, which definitely allowed this.

Does nog support this already? If so, how?
If not, consider this a feature request.

Thanks!

### PR DESCRIPTION
**Pull request by ramirezmike**
This addresses #264

### CODE REVIEW

**Comment by TimUntersberger** [comment]
Did you rebuild the docs?

**Comment by ramirezmike** [comment]
> Did you rebuild the docs?

Right, I ran build_docs.ps1... I recently replaced my OS and reinstalled everything so I'm not sure if it's just an updated version of things but it looks like it made a lot of changes that are like... setting the ID attributes on elements and some differences in the css. Not sure if you want all that in there too? Let me know and I can redo that if needed.

**Comment by ramirezmike** [comment]
@TimUntersberger 

What do you think of the doc generation part of this PR? I have mdbook v0.4.7 installed.. it looks like it made a lot of changes like this

```<h1><a class="header" href="#array" id="array">Array</a></h1>```
to this 
```<h1 id="array"><a class="header" href="#array">Array</a></h1>```

where it moves the ID prop from the \<a> tag to the \<h1> tag. I _think_ it might just be because of some change in mdbook. If you have the same version installed then maybe it's something else that caused it. I just don't want to introduce something that adds a lot of noise and gets done/undone any time someone re-runs the doc gen.

**Comment by TimUntersberger** [comment]
As long as everything is displayed correctly it should be fine.

**Comment by ramirezmike** [comment]
Alright.

Also, I'm planning on waiting until your lua branch gets finished and then patching my open PRs rather than like... shoving stuff in that might start causing more confusion for now. It'll be easier that way, I think + might work better with my schedule right now.

**Comment by ramirezmike** [comment]
Ok, this is an updated version of this PR post-lua changes. I'll merge it in a day or two if no one objects.

**Review by TimUntersberger — APPROVED** [review]

**Comment by TimUntersberger** [comment]
A small tip: if you want to close an issue once this pr is merged you can add `closes #264` to the description.

**Pull request merged**
